title: GM-Dev - Michel Guillon
email: your-email@example.com
description: Développeur freelance C++
header:
  title: GM-Dev - Michel Guillon
  description: >- # this means to ignore newlines until "baseurl:"
    Développeur freelance C++

baseurl: "" # the subpath of your site, e.g. /blog
url: "https://michel-guillon.fr"
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
# theme: minima
plugins:
  - jekyll-seo-tag
  - jemoji
  - jekyll-sitemap

defaults:
  - scope:
      path: assets/**
    values:
      sitemap: false


# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
social:
  github: michel-guillon

GM-Dev:
  location: Mably, FRANCE
  links:
    github:
      title: github
      url: https://github.com/michel-guillon
    blog:
      title: Blog GM-Dev
      url: https://michel-guillon.github.io/gm-dev.github.io/projects

collections:
  skills:
    output: false
  soft_skills:
    output: false
  projects:
    output: true
    permalink: /project/:path/
  experiences:
    output: true
  certifications:
    output: true
    permalink: /certification/:path/


